---
downloads: ~/.ansible-downloads/

configure_dock: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes
configure_oh_my_zsh: yes

configure_iterm: yes
iterm2_overwite_configuration: no

dotfiles_repo: https://github.com/blimmer/dotfiles
dotfiles_repo_accept_hostkey: no
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore_global
  - .osx
  - .tmux.conf
  - .zshrc

homebrew_installed_packages:
  - ack
  - awscli
  - bats
  - coreutils
  - curl
  - diff-so-fancy
  - ffmpeg
  - git
  - go
  - gpg
  - highlight
  - hub
  - jq
  - kubernetes-cli
  - sqlite
  - mas
  - minikube
  - npm
  - nvm
  - openssl
  - pinentry
  - python
  - python3
  - ssh-copy-id
  - rbenv
  - readline
  - ruby-build
  - s3cmd
  - the_silver_searcher
  - tldr
  - tmux
  - tree
  - vim
  - wget
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - aws-vault
  - docker
  - firefox-beta
  - font-menlo-for-powerline
  - google-chrome
  - graphiql
  - iterm2
  - keepingyouawake
  - slack
  - spotify
  - the-unarchiver
  - virtualbox
  - virtualbox-extension-pack

dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar

dockitems_enabled:
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 3
  - name: Messages
    path: "/Applications/Messages.app"
    pos: 4
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 5
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 6
