---
downloads: ~/.ansible-downloads/

configure_dock: true
configure_terminal: false
configure_osx: true
configure_oh_my_zsh: true

configure_iterm: true

dotfiles_repo: https://github.com/blimmer/dotfiles
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .asdfrc
  - .gitconfig
  - .gitignore_global
  - .osx
  - .tool-versions
  - .zshrc

homebrew_installed_packages:
  - ack
  - asdf
  - awscli
  - bat
  - coreutils
  - curl
  - ffmpeg
  - git
  - go
  - gpg
  - hadolint
  - highlight
  - jq
  - openssl
  - python3
  - shellcheck
  - ssh-copy-id
  - readline
  - ruby-build
  - tfenv
  - the_silver_searcher
  - tldr
  - tree
  - vim
  - wget
  - zsh

homebrew_taps:
  - homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - aws-vault
  - docker
  - firefox@beta
  - font-menlo-for-powerline
  - google-chrome
  - imageoptim
  - istat-menus@6
  - iterm2
  - keepingyouawake
  - obsidian
  - pastebot
  - rectangle
  - slack
  - spotify
  - stretchly
  - visual-studio-code
  - zoom

dockitems_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Music
  - Podcasts
  - TV
  - News
  - App Store
  - System Preferences
  - Calendar

dockitems_persist:
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 1
  - name: Messages
    path: "/System/Applications/Messages.app"
    pos: 2
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 5
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 6
