---
downloads: ~/.ansible-downloads/

configure_dock: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes
configure_oh_my_zsh: yes

configure_iterm: yes

dotfiles_repo: https://github.com/blimmer/dotfiles
dotfiles_repo_accept_hostkey: no
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .asdfrc
  - .gitconfig
  - .gitignore_global
  - .osx
  - .tool-versions
  - .tmux.conf
  - .zshrc

homebrew_installed_packages:
  - ack
  - asdf
  - awscli
  - bats
  - coreutils
  - curl
  - diff-so-fancy
  - git
  - go
  - gpg
  - highlight
  - hub
  - jq
  - kubernetes-cli
  - sqlite
  - mas
  - minikube
  - npm
  - openssl
  - pinentry
  - python3
  - ssh-copy-id
  - readline
  - s3cmd
  - the_silver_searcher
  - tldr
  - tmux
  - tree
  - vim
  - wget
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - aws-vault
  - docker
  - firefox-beta
  - font-menlo-for-powerline
  - google-chrome
  - graphiql
  - imageoptim
  - istat-menus
  - iterm2
  - keepingyouawake
  - slack
  - spectacle
  - spotify
  - visual-studio-code

dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Music
  - Podcasts
  - TV
  - News
  - App Store
  - System Preferences
  - Calendar

dockitems_enabled:
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 3
  - name: Messages
    path: "/System/Applications/Messages.app"
    pos: 4
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 5
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 6
