---
# ruby things

- name: Ensure ruby homebrew packages are installed.
  homebrew: "name={{ item }} state=present"
  with_items:
    - rbenv
    - ruby-build

- name: Install Ruby version {{ global_rbenv_ruby_version }}
  shell: $SHELL -lc "rbenv install {{ global_rbenv_ruby_version }}"
  args:
    creates: "{{ rbenv_root }}/versions/{{ global_rbenv_ruby_version }}/bin/ruby"
  when: global_rbenv_ruby_version is defined

- name: Set fact for global ruby version
  set_fact:
    current_global_rbenv_ruby_version: "{{ lookup('file', {{ rbenv_root }}/version) }}"

- name: Set global ruby version to {{ global_rbenv_ruby_version }}
  shell: $SHELL -lc "rbenv global {{global_rbenv_ruby_version}}"
  when: global_rbenv_ruby_version is defined and current_global_rbenv_ruby_version != global_rbenv_ruby_version
